OBJCC = xcrun --sdk iphonesimulator clang -target arm64-apple-ios13.0-simulator
OBJCLD_SHARED = $(OBJCC) -shared

OBJCLDFLAGS = -fobjc-link-runtime -framework CoreGraphics

OUTPUT_DIR = build
TESTS_DIR = ../../tests
OBJECTS_DIR = $(OUTPUT_DIR)/objects/iphonesimulator

HEADER_FILES = $(wildcard *.h)
SOURCE_FILES = $(wildcard *.m)
OBJ_FILES = $(addprefix $(OBJECTS_DIR)/,$(addsuffix .o,$(SOURCE_FILES)))

LIB_NAME = librubiconharness-arm64-iphonesimulator.so

all: $(TESTS_DIR)/$(LIB_NAME)

$(TESTS_DIR)/$(LIB_NAME): $(OBJ_FILES)
	@mkdir -p $(@D)
	$(OBJCLD_SHARED) $(OBJCLDFLAGS) $(OBJ_FILES) $(OBJCLDLIBS) -o $@

clean:
	$(RM) -r $(OUTPUT_DIR)

$(OBJECTS_DIR)/%.m.o: %.m $(HEADER_FILES)
	@mkdir -p $(@D)
	$(OBJCC) $(OBJCFLAGS) -c $< -o $@
