name: Dependabot Change Note

on:
  push:
    branches:
      - 'dependabot/**'

jobs:
  changenote:
    name: Dependabot Change Note
    permissions:
      contents: read
      pull-requests: write
    uses: beeware/.github/.github/workflows/dependabot-changenote.yml@main
    secrets:
      BRUTUS_PAT_TOKEN: ${{ secrets.BRUTUS_PAT_TOKEN }}
    with:
      changenote-format: "md"
