name: Create Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  ci:
    name: CI
    permissions:
      contents: read
      id-token: write
      attestations: write
      pull-requests: write
    uses: ./.github/workflows/ci.yml
    with:
      attest-package: "true"

  docs:
    name: Verify Docs Build
    permissions:
      contents: read
    uses: beeware/.github/.github/workflows/docs-build-verify.yml@main
    secrets:
      RTD_API_TOKEN: ${{ secrets.RTD_API_TOKEN }}
    with:
      project-name: "rubicon-objc"
      project-version: ${{ github.ref_name }}

  release:
    name: Create Release
    needs: [ ci, docs ]
    # This has to be run on macOS, because rubicon tries to load the Foundation library
    runs-on: macOS-latest
    permissions:
      contents: write
    steps:
      - name: Set build variables
        run: |
          echo "VERSION=${GITHUB_REF_NAME#v}" | tee -a $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: "3.X"

      - name: Get packages
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
        with:
          name: ${{ needs.ci.outputs.artifact-name }}
          path: dist

      - name: Install packages
        run: python -m pip install dist/rubicon_objc-*.whl

      - name: Check version number
        # Check that the setuptools_scm-generated version number is still the same when
        # installed from a wheel with setuptools_scm not present.
        run: |
          set -x
          test $(python -c "from rubicon.objc import __version__; print(__version__)") = $VERSION

      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: |
          gh release create "${GITHUB_REF_NAME}" \
            --title "${VERSION}" \
            --draft \
            --verify-tag \
            dist/*

  test-publish:
    name: Publish test package
    needs: [ ci, docs, release ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      # This permission is required for trusted publishing.
      id-token: write
    steps:
      - name: Get packages
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
        with:
          name: ${{ needs.ci.outputs.artifact-name }}
          path: dist

      - name: Publish release to Test PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33  # v1.14.2
        with:
          repository-url: https://test.pypi.org/legacy/
